add_executable(logger_tests logger_test.cpp)
target_link_libraries(logger_tests PRIVATE logger::logger)
target_compile_options(logger_tests PRIVATE -Wall -Wextra -Wpedantic -UNDEBUG)
add_test(NAME logger_tests COMMAND logger_tests)

add_executable(statistics_tests statistics_test.cpp)
target_include_directories(statistics_tests PRIVATE ${PROJECT_SOURCE_DIR}/collector)
target_link_libraries(statistics_tests PRIVATE logger::logger)
target_compile_options(statistics_tests PRIVATE -Wall -Wextra -Wpedantic -UNDEBUG)
add_test(NAME statistics_tests COMMAND statistics_tests)

add_executable(collector_tests collector_test.cpp)
target_link_libraries(collector_tests PRIVATE logger::logger)
target_compile_options(collector_tests PRIVATE -Wall -Wextra -Wpedantic -UNDEBUG)
add_test(NAME collector_tests COMMAND collector_tests)
